# Generated by Django 4.2.5 on 2023-09-22 09:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0016_remove_cart_product_remove_cart_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="order",
            fields=[
                ("secret_key", models.CharField(max_length=20)),
                ("order_id", models.AutoField(primary_key=True, serialize=False)),
                ("final_price", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[("1", "delieverd"), ("2", "not delieverd")],
                        default="2",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 9, 22, 9, 18, 16, 159109, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                ("order_placed", models.BooleanField(default=0)),
                ("expired", models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="product_order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.order"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="products.product",
                    ),
                ),
            ],
        ),
    ]
