# Generated by Django 4.2.5 on 2023-09-22 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 22, 9, 30, 29, 787308, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
