# Generated by Django 4.2.4 on 2023-08-16 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_user_managers_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
