# Generated by Django 4.2.4 on 2023-08-17 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_order_discount_remove_order_payment_method_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.AddField(
            model_name='order',
            name='secret_key',
            field=models.CharField(default='sssss', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 10, 3, 34, 520444, tzinfo=datetime.timezone.utc)),
        ),
    ]
