# Generated by Django 4.2.4 on 2023-08-17 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_order_quantity_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expired',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 22, 34, 29, 586095, tzinfo=datetime.timezone.utc)),
        ),
    ]
