# Generated by Django 4.2.4 on 2023-09-04 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_alter_cart_quantity_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 4, 6, 31, 17, 765485, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
