# Generated by Django 4.2.4 on 2023-09-05 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_user_is_deleted_alter_order_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="product_order",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 5, 11, 1, 30, 792106, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
