# Generated by Django 4.2.4 on 2023-09-05 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_product_order_price_alter_order_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 9, 5, 11, 49, 44, 89766, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
