# Generated by Django 4.2.5 on 2023-09-22 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_alter_order_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="product",
        ),
        migrations.RemoveField(
            model_name="cart",
            name="user",
        ),
        migrations.RemoveField(
            model_name="order",
            name="del_adress",
        ),
        migrations.RemoveField(
            model_name="order",
            name="user",
        ),
        migrations.RemoveField(
            model_name="product_order",
            name="order",
        ),
        migrations.RemoveField(
            model_name="product_order",
            name="product",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="adress",
        ),
        migrations.DeleteModel(
            name="cart",
        ),
        migrations.DeleteModel(
            name="order",
        ),
        migrations.DeleteModel(
            name="product_order",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
